name: raylib_dartified_base
description: Shared types and abstractions for the raylib_dartified package family.
version: 5.5.2
repository: https://github.com/TheNoiselessNoise/raylib_dartified_base

environment:
  sdk: ^3.10.7

dependencies:
  path: ^1.9.0
  meta: ^1.18.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
