import 'package:raylib_dartified_base/raylib_dartified_base.dart';

/// See [RaylibGuiConstants.RAYGUI_VERSION_MAJOR].
int get RAYGUI_VERSION_MAJOR => RaylibGuiConstants.RAYGUI_VERSION_MAJOR;

/// See [RaylibGuiConstants.RAYGUI_VERSION_MINOR].
int get RAYGUI_VERSION_MINOR => RaylibGuiConstants.RAYGUI_VERSION_MINOR;

/// See [RaylibGuiConstants.RAYGUI_VERSION_PATCH].
int get RAYGUI_VERSION_PATCH => RaylibGuiConstants.RAYGUI_VERSION_PATCH;

/// See [RaylibGuiConstants.RAYGUI_VERSION].
String get RAYGUI_VERSION => RaylibGuiConstants.RAYGUI_VERSION;

/// See [RaylibGuiConstants.RAYGUI_SCROLLBAR_LEFT_SIDE].
int get RAYGUI_SCROLLBAR_LEFT_SIDE => RaylibGuiConstants.RAYGUI_SCROLLBAR_LEFT_SIDE;

/// See [RaylibGuiConstants.RAYGUI_SCROLLBAR_RIGHT_SIDE].
int get RAYGUI_SCROLLBAR_RIGHT_SIDE => RaylibGuiConstants.RAYGUI_SCROLLBAR_RIGHT_SIDE;

/// See [RaylibGuiConstants.RAYGUI_ICON_SIZE].
int get RAYGUI_ICON_SIZE => RaylibGuiConstants.RAYGUI_ICON_SIZE;

/// See [RaylibGuiConstants.RAYGUI_ICON_MAX_ICONS].
int get RAYGUI_ICON_MAX_ICONS => RaylibGuiConstants.RAYGUI_ICON_MAX_ICONS;

/// See [RaylibGuiConstants.RAYGUI_ICON_MAX_NAME_LENGTH].
int get RAYGUI_ICON_MAX_NAME_LENGTH => RaylibGuiConstants.RAYGUI_ICON_MAX_NAME_LENGTH;

/// See [RaylibGuiConstants.RAYGUI_ICON_DATA_ELEMENTS].
int get RAYGUI_ICON_DATA_ELEMENTS => RaylibGuiConstants.RAYGUI_ICON_DATA_ELEMENTS;

/// See [RaylibGuiConstants.RAYGUI_MAX_CONTROLS].
int get RAYGUI_MAX_CONTROLS => RaylibGuiConstants.RAYGUI_MAX_CONTROLS;

/// See [RaylibGuiConstants.RAYGUI_MAX_PROPS_BASE].
int get RAYGUI_MAX_PROPS_BASE => RaylibGuiConstants.RAYGUI_MAX_PROPS_BASE;

/// See [RaylibGuiConstants.RAYGUI_MAX_PROPS_EXTENDED].
int get RAYGUI_MAX_PROPS_EXTENDED => RaylibGuiConstants.RAYGUI_MAX_PROPS_EXTENDED;

/// See [RaylibGuiConstants.RAYGUI_WINDOWBOX_STATUSBAR_HEIGHT].
int get RAYGUI_WINDOWBOX_STATUSBAR_HEIGHT => RaylibGuiConstants.RAYGUI_WINDOWBOX_STATUSBAR_HEIGHT;

/// See [RaylibGuiConstants.RAYGUI_GROUPBOX_LINE_THICK].
int get RAYGUI_GROUPBOX_LINE_THICK => RaylibGuiConstants.RAYGUI_GROUPBOX_LINE_THICK;

/// See [RaylibGuiConstants.RAYGUI_LINE_MARGIN_TEXT].
int get RAYGUI_LINE_MARGIN_TEXT => RaylibGuiConstants.RAYGUI_LINE_MARGIN_TEXT;

/// See [RaylibGuiConstants.RAYGUI_LINE_TEXT_PADDING].
int get RAYGUI_LINE_TEXT_PADDING => RaylibGuiConstants.RAYGUI_LINE_TEXT_PADDING;

/// See [RaylibGuiConstants.RAYGUI_PANEL_BORDER_WIDTH].
int get RAYGUI_PANEL_BORDER_WIDTH => RaylibGuiConstants.RAYGUI_PANEL_BORDER_WIDTH;

/// See [RaylibGuiConstants.RAYGUI_TABBAR_ITEM_WIDTH].
int get RAYGUI_TABBAR_ITEM_WIDTH => RaylibGuiConstants.RAYGUI_TABBAR_ITEM_WIDTH;

/// See [RaylibGuiConstants.RAYGUI_MIN_SCROLLBAR_WIDTH].
int get RAYGUI_MIN_SCROLLBAR_WIDTH => RaylibGuiConstants.RAYGUI_MIN_SCROLLBAR_WIDTH;

/// See [RaylibGuiConstants.RAYGUI_MIN_SCROLLBAR_HEIGHT].
int get RAYGUI_MIN_SCROLLBAR_HEIGHT => RaylibGuiConstants.RAYGUI_MIN_SCROLLBAR_HEIGHT;

/// See [RaylibGuiConstants.RAYGUI_MIN_MOUSE_WHEEL_SPEED].
int get RAYGUI_MIN_MOUSE_WHEEL_SPEED => RaylibGuiConstants.RAYGUI_MIN_MOUSE_WHEEL_SPEED;

/// See [RaylibGuiConstants.RAYGUI_TOGGLEGROUP_MAX_ITEMS].
int get RAYGUI_TOGGLEGROUP_MAX_ITEMS => RaylibGuiConstants.RAYGUI_TOGGLEGROUP_MAX_ITEMS;

/// See [RaylibGuiConstants.RAYGUI_TEXTBOX_AUTO_CURSOR_COOLDOWN].
int get RAYGUI_TEXTBOX_AUTO_CURSOR_COOLDOWN => RaylibGuiConstants.RAYGUI_TEXTBOX_AUTO_CURSOR_COOLDOWN;

/// See [RaylibGuiConstants.RAYGUI_TEXTBOX_AUTO_CURSOR_DELAY].
int get RAYGUI_TEXTBOX_AUTO_CURSOR_DELAY => RaylibGuiConstants.RAYGUI_TEXTBOX_AUTO_CURSOR_DELAY;

/// See [RaylibGuiConstants.RAYGUI_VALUEBOX_MAX_CHARS].
int get RAYGUI_VALUEBOX_MAX_CHARS => RaylibGuiConstants.RAYGUI_VALUEBOX_MAX_CHARS;

/// See [RaylibGuiConstants.RAYGUI_COLORBARALPHA_CHECKED_SIZE].
int get RAYGUI_COLORBARALPHA_CHECKED_SIZE => RaylibGuiConstants.RAYGUI_COLORBARALPHA_CHECKED_SIZE;

/// See [RaylibGuiConstants.RAYGUI_MESSAGEBOX_BUTTON_HEIGHT].
int get RAYGUI_MESSAGEBOX_BUTTON_HEIGHT => RaylibGuiConstants.RAYGUI_MESSAGEBOX_BUTTON_HEIGHT;

/// See [RaylibGuiConstants.RAYGUI_MESSAGEBOX_BUTTON_PADDING].
int get RAYGUI_MESSAGEBOX_BUTTON_PADDING => RaylibGuiConstants.RAYGUI_MESSAGEBOX_BUTTON_PADDING;

/// See [RaylibGuiConstants.RAYGUI_TEXTINPUTBOX_BUTTON_HEIGHT].
int get RAYGUI_TEXTINPUTBOX_BUTTON_HEIGHT => RaylibGuiConstants.RAYGUI_TEXTINPUTBOX_BUTTON_HEIGHT;

/// See [RaylibGuiConstants.RAYGUI_TEXTINPUTBOX_BUTTON_PADDING].
int get RAYGUI_TEXTINPUTBOX_BUTTON_PADDING => RaylibGuiConstants.RAYGUI_TEXTINPUTBOX_BUTTON_PADDING;

/// See [RaylibGuiConstants.RAYGUI_TEXTINPUTBOX_HEIGHT].
int get RAYGUI_TEXTINPUTBOX_HEIGHT => RaylibGuiConstants.RAYGUI_TEXTINPUTBOX_HEIGHT;

/// See [RaylibGuiConstants.RAYGUI_GRID_ALPHA].
double get RAYGUI_GRID_ALPHA => RaylibGuiConstants.RAYGUI_GRID_ALPHA;

/// See [RaylibGuiConstants.RAYGUI_MAX_LINE_BUFFER_SIZE].
int get RAYGUI_MAX_LINE_BUFFER_SIZE => RaylibGuiConstants.RAYGUI_MAX_LINE_BUFFER_SIZE;

/// See [RaylibGuiConstants.RAYGUI_ICON_TEXT_PADDING].
int get RAYGUI_ICON_TEXT_PADDING => RaylibGuiConstants.RAYGUI_ICON_TEXT_PADDING;

/// See [RaylibGuiConstants.RAYGUI_MAX_TEXT_LINES].
int get RAYGUI_MAX_TEXT_LINES => RaylibGuiConstants.RAYGUI_MAX_TEXT_LINES;

/// See [RaylibGuiConstants.RAYGUI_TEXTSPLIT_MAX_ITEMS].
int get RAYGUI_TEXTSPLIT_MAX_ITEMS => RaylibGuiConstants.RAYGUI_TEXTSPLIT_MAX_ITEMS;

/// See [RaylibGuiConstants.RAYGUI_TEXTSPLIT_MAX_TEXT_SIZE].
int get RAYGUI_TEXTSPLIT_MAX_TEXT_SIZE => RaylibGuiConstants.RAYGUI_TEXTSPLIT_MAX_TEXT_SIZE;

/// See [RaylibGuiConstants.RAYGUI_TEXTFORMAT_MAX_SIZE].
int get RAYGUI_TEXTFORMAT_MAX_SIZE => RaylibGuiConstants.RAYGUI_TEXTFORMAT_MAX_SIZE;

/// See [RaylibGuiConstants.RAYGUI_ICONS].
/// Predefined constant `RAYGUI_ICONS`.
List<int> get RAYGUI_ICONS => RaylibGuiConstants.RAYGUI_ICONS;
