part of '../../raylib_dartified_base.dart';

/// Backend-agnostic contract for the Raylib Rlgl module.
///
/// Concrete platform implementations mix in or extend this to provide
/// the full API surface across different backends.
final class RaylibRlglModule<R extends RaylibBase<R>> extends RaylibModule<R> with RaylibRlglModuleExtras<R> {

  final _debugLabels = _RaylibRlglModuleDebugLabels();

  RaylibRlglModule(super.rl);

  /// Choose the current matrix to be transformed
  void rlMatrixMode(
    RlMatrixMode mode,
  ) => run(
    () => _debugLabels.rlMatrixMode(mode),
    () => rl.RlglFlat.rlMatrixMode(
      mode.value,
    ),
  );

  /// Push the current matrix to stack
  void rlPushMatrix() => run(
    () => _debugLabels.rlPushMatrix(),
    () => rl.RlglFlat.rlPushMatrix(),
  );

  /// Pop latest inserted matrix from stack
  void rlPopMatrix() => run(
    () => _debugLabels.rlPopMatrix(),
    () => rl.RlglFlat.rlPopMatrix(),
  );

  /// Reset current matrix to identity matrix
  void rlLoadIdentity() => run(
    () => _debugLabels.rlLoadIdentity(),
    () => rl.RlglFlat.rlLoadIdentity(),
  );

  /// Multiply the current matrix by a translation matrix
  void rlTranslatef(
    num x,
    num y,
    num z,
  ) => run(
    () => _debugLabels.rlTranslatef(x, y, z),
    () => rl.RlglFlat.rlTranslatef(
      x.toDouble(),
      y.toDouble(),
      z.toDouble(),
    ),
  );

  /// Multiply the current matrix by a rotation matrix
  void rlRotatef(
    num angle,
    num x,
    num y,
    num z,
  ) => run(
    () => _debugLabels.rlRotatef(angle, x, y, z),
    () => rl.RlglFlat.rlRotatef(
      angle.toDouble(),
      x.toDouble(),
      y.toDouble(),
      z.toDouble(),
    ),
  );

  /// Multiply the current matrix by a scaling matrix
  void rlScalef(
    num x,
    num y,
    num z,
  ) => run(
    () => _debugLabels.rlScalef(x, y, z),
    () => rl.RlglFlat.rlScalef(
      x.toDouble(),
      y.toDouble(),
      z.toDouble(),
    ),
  );

  /// Multiply the current matrix by another matrix
  void rlMultMatrixf(
    List<num> matf,
  ) => run(
    () => _debugLabels.rlMultMatrixf(matf),
    () => rl.RlglFlat.rlMultMatrixf(
      rl.Temp.Float32$.Array(matf),
    ),
  );

  /// Multiply the current matrix by a perspective matrix generated by parameters
  void rlFrustum(
    num left,
    num right,
    num bottom,
    num top,
    num znear,
    num zfar,
  ) => run(
    () => _debugLabels.rlFrustum(left, right, bottom, top, znear, zfar),
    () => rl.RlglFlat.rlFrustum(
      left.toDouble(),
      right.toDouble(),
      bottom.toDouble(),
      top.toDouble(),
      znear.toDouble(),
      zfar.toDouble(),
    ),
  );

  /// Multiply the current matrix by an orthographic matrix generated by parameters
  void rlOrtho(
    num left,
    num right,
    num bottom,
    num top,
    num znear,
    num zfar,
  ) => run(
    () => _debugLabels.rlOrtho(left, right, bottom, top, znear, zfar),
    () => rl.RlglFlat.rlOrtho(
      left.toDouble(),
      right.toDouble(),
      bottom.toDouble(),
      top.toDouble(),
      znear.toDouble(),
      zfar.toDouble(),
    ),
  );

  /// Set the viewport area
  void rlViewport(
    num x,
    num y,
    num width,
    num height,
  ) => run(
    () => _debugLabels.rlViewport(x, y, width, height),
    () => rl.RlglFlat.rlViewport(
      x.toInt(),
      y.toInt(),
      width.toInt(),
      height.toInt(),
    ),
  );

  /// Set clip planes distances
  void rlSetClipPlanes(
    num nearPlane,
    num farPlane,
  ) => run(
    () => _debugLabels.rlSetClipPlanes(nearPlane, farPlane),
    () => rl.RlglFlat.rlSetClipPlanes(
      nearPlane.toDouble(),
      farPlane.toDouble(),
    ),
  );

  /// Get cull plane distance near
  double rlGetCullDistanceNear() => run(
    () => _debugLabels.rlGetCullDistanceNear(),
    () => rl.RlglFlat.rlGetCullDistanceNear(),
  );

  /// Get cull plane distance far
  double rlGetCullDistanceFar() => run(
    () => _debugLabels.rlGetCullDistanceFar(),
    () => rl.RlglFlat.rlGetCullDistanceFar(),
  );

  /// Initialize drawing mode (how to organize vertex)
  void rlBegin(
    RlDrawMode mode,
  ) => run(
    () => _debugLabels.rlBegin(mode),
    () => rl.RlglFlat.rlBegin(
      mode.value,
    ),
  );

  /// Finish vertex providing
  void rlEnd() => run(
    () => _debugLabels.rlEnd(),
    () => rl.RlglFlat.rlEnd(),
  );

  /// Define one vertex (position) - 2 int
  void rlVertex2i(
    num x,
    num y,
  ) => run(
    () => _debugLabels.rlVertex2i(x, y),
    () => rl.RlglFlat.rlVertex2i(
      x.toInt(),
      y.toInt(),
    ),
  );

  /// Define one vertex (position) - 2 float
  void rlVertex2f(
    num x,
    num y,
  ) => run(
    () => _debugLabels.rlVertex2f(x, y),
    () => rl.RlglFlat.rlVertex2f(
      x.toDouble(),
      y.toDouble(),
    ),
  );

  /// Define one vertex (position) - 3 float
  void rlVertex3f(
    num x,
    num y,
    num z,
  ) => run(
    () => _debugLabels.rlVertex3f(x, y, z),
    () => rl.RlglFlat.rlVertex3f(
      x.toDouble(),
      y.toDouble(),
      z.toDouble(),
    ),
  );

  /// Define one vertex (texture coordinate) - 2 float
  void rlTexCoord2f(
    num x,
    num y,
  ) => run(
    () => _debugLabels.rlTexCoord2f(x, y),
    () => rl.RlglFlat.rlTexCoord2f(
      x.toDouble(),
      y.toDouble(),
    ),
  );

  /// Define one vertex (normal) - 3 float
  void rlNormal3f(
    num x,
    num y,
    num z,
  ) => run(
    () => _debugLabels.rlNormal3f(x, y, z),
    () => rl.RlglFlat.rlNormal3f(
      x.toDouble(),
      y.toDouble(),
      z.toDouble(),
    ),
  );

  /// Define one vertex (color) - 4 byte
  void rlColor4ub(
    num r,
    num g,
    num b,
    num a,
  ) => run(
    () => _debugLabels.rlColor4ub(r, g, b, a),
    () => rl.RlglFlat.rlColor4ub(
      r.toInt(),
      g.toInt(),
      b.toInt(),
      a.toInt(),
    ),
  );

  /// Define one vertex (color) - 3 float
  void rlColor3f(
    num x,
    num y,
    num z,
  ) => run(
    () => _debugLabels.rlColor3f(x, y, z),
    () => rl.RlglFlat.rlColor3f(
      x.toDouble(),
      y.toDouble(),
      z.toDouble(),
    ),
  );

  /// Define one vertex (color) - 4 float
  void rlColor4f(
    num x,
    num y,
    num z,
    num w,
  ) => run(
    () => _debugLabels.rlColor4f(x, y, z, w),
    () => rl.RlglFlat.rlColor4f(
      x.toDouble(),
      y.toDouble(),
      z.toDouble(),
      w.toDouble(),
    ),
  );

  /// Enable vertex array (VAO, if supported)
  bool rlEnableVertexArray(
    num vaoId,
  ) => run(
    () => _debugLabels.rlEnableVertexArray(vaoId),
    () => rl.RlglFlat.rlEnableVertexArray(
      vaoId.toInt(),
    ),
  );

  /// Disable vertex array (VAO, if supported)
  void rlDisableVertexArray() => run(
    () => _debugLabels.rlDisableVertexArray(),
    () => rl.RlglFlat.rlDisableVertexArray(),
  );

  /// Enable vertex buffer (VBO)
  void rlEnableVertexBuffer(
    num id,
  ) => run(
    () => _debugLabels.rlEnableVertexBuffer(id),
    () => rl.RlglFlat.rlEnableVertexBuffer(
      id.toInt(),
    ),
  );

  /// Disable vertex buffer (VBO)
  void rlDisableVertexBuffer() => run(
    () => _debugLabels.rlDisableVertexBuffer(),
    () => rl.RlglFlat.rlDisableVertexBuffer(),
  );

  /// Enable vertex buffer element (VBO element)
  void rlEnableVertexBufferElement(
    num id,
  ) => run(
    () => _debugLabels.rlEnableVertexBufferElement(id),
    () => rl.RlglFlat.rlEnableVertexBufferElement(
      id.toInt(),
    ),
  );

  /// Disable vertex buffer element (VBO element)
  void rlDisableVertexBufferElement() => run(
    () => _debugLabels.rlDisableVertexBufferElement(),
    () => rl.RlglFlat.rlDisableVertexBufferElement(),
  );

  /// Enable vertex attribute index
  void rlEnableVertexAttribute(
    num index,
  ) => run(
    () => _debugLabels.rlEnableVertexAttribute(index),
    () => rl.RlglFlat.rlEnableVertexAttribute(
      index.toInt(),
    ),
  );

  /// Disable vertex attribute index
  void rlDisableVertexAttribute(
    num index,
  ) => run(
    () => _debugLabels.rlDisableVertexAttribute(index),
    () => rl.RlglFlat.rlDisableVertexAttribute(
      index.toInt(),
    ),
  );

  final Map<int, MemoryPointer> _rlEnableStatePointer_statePointers = {};

  /// Enable attribute state pointer
  void rlEnableStatePointer(int vertexAttribType, TypedDataList buffer) => run(
    () => _debugLabels.rlEnableStatePointer(vertexAttribType, buffer),
    () {
      final existing = _rlEnableStatePointer_statePointers[vertexAttribType];
      if (existing != null) existing.free();

      final native = rl.Temp.TypedDataList$.Array(buffer, key: 'rlEnableStatePointer_$vertexAttribType');

      _rlEnableStatePointer_statePointers[vertexAttribType] = native;

      rl.RlglFlat.rlEnableStatePointer(
        vertexAttribType,
        native,
      );
    },
  );

  /// Disable attribute state pointer
  void rlDisableStatePointer(int vertexAttribType) => run(
    () => _debugLabels.rlDisableStatePointer(vertexAttribType),
    () {
      rl.RlglFlat.rlDisableStatePointer(
        vertexAttribType,
      );

      final existing = _rlEnableStatePointer_statePointers.remove(vertexAttribType);
      if (existing != null) existing.free();
    },
  );

  /// Select and active a texture slot
  void rlActiveTextureSlot(
    num slot,
  ) => run(
    () => _debugLabels.rlActiveTextureSlot(slot),
    () => rl.RlglFlat.rlActiveTextureSlot(
      slot.toInt(),
    ),
  );

  /// Enable texture
  void rlEnableTexture(
    num id,
  ) => run(
    () => _debugLabels.rlEnableTexture(id),
    () => rl.RlglFlat.rlEnableTexture(
      id.toInt(),
    ),
  );

  /// Disable texture
  void rlDisableTexture() => run(
    () => _debugLabels.rlDisableTexture(),
    () => rl.RlglFlat.rlDisableTexture(),
  );

  /// Enable texture cubemap
  void rlEnableTextureCubemap(
    num id,
  ) => run(
    () => _debugLabels.rlEnableTextureCubemap(id),
    () => rl.RlglFlat.rlEnableTextureCubemap(
      id.toInt(),
    ),
  );

  /// Disable texture cubemap
  void rlDisableTextureCubemap() => run(
    () => _debugLabels.rlDisableTextureCubemap(),
    () => rl.RlglFlat.rlDisableTextureCubemap(),
  );

  /// Set texture parameters (filter, wrap)
  void rlTextureParameters(
    num id,
    num param,
    num value,
  ) => run(
    () => _debugLabels.rlTextureParameters(id, param, value),
    () => rl.RlglFlat.rlTextureParameters(
      id.toInt(),
      param.toInt(),
      value.toInt(),
    ),
  );

  /// Set cubemap parameters (filter, wrap)
  void rlCubemapParameters(
    num id,
    num param,
    num value,
  ) => run(
    () => _debugLabels.rlCubemapParameters(id, param, value),
    () => rl.RlglFlat.rlCubemapParameters(
      id.toInt(),
      param.toInt(),
      value.toInt(),
    ),
  );

  /// Enable shader program
  void rlEnableShader(
    num id,
  ) => run(
    () => _debugLabels.rlEnableShader(id),
    () => rl.RlglFlat.rlEnableShader(
      id.toInt(),
    ),
  );

  /// Disable shader program
  void rlDisableShader() => run(
    () => _debugLabels.rlDisableShader(),
    () => rl.RlglFlat.rlDisableShader(),
  );

  /// Enable render texture (fbo)
  void rlEnableFramebuffer(
    num id,
  ) => run(
    () => _debugLabels.rlEnableFramebuffer(id),
    () => rl.RlglFlat.rlEnableFramebuffer(
      id.toInt(),
    ),
  );

  /// Disable render texture (fbo), return to default framebuffer
  void rlDisableFramebuffer() => run(
    () => _debugLabels.rlDisableFramebuffer(),
    () => rl.RlglFlat.rlDisableFramebuffer(),
  );

  /// Get the currently active render texture (fbo), 0 for default framebuffer
  int rlGetActiveFramebuffer() => run(
    () => _debugLabels.rlGetActiveFramebuffer(),
    () => rl.RlglFlat.rlGetActiveFramebuffer(),
  );

  /// Activate multiple draw color buffers
  void rlActiveDrawBuffers(
    num count,
  ) => run(
    () => _debugLabels.rlActiveDrawBuffers(count),
    () => rl.RlglFlat.rlActiveDrawBuffers(
      count.toInt(),
    ),
  );

  /// Blit active framebuffer to main framebuffer
  void rlBlitFramebuffer(
    num srcX,
    num srcY,
    num srcWidth,
    num srcHeight,
    num dstX,
    num dstY,
    num dstWidth,
    num dstHeight,
    num bufferMask,
  ) => run(
    () => _debugLabels.rlBlitFramebuffer(srcX, srcY, srcWidth, srcHeight, dstX, dstY, dstWidth, dstHeight, bufferMask),
    () => rl.RlglFlat.rlBlitFramebuffer(
      srcX.toInt(),
      srcY.toInt(),
      srcWidth.toInt(),
      srcHeight.toInt(),
      dstX.toInt(),
      dstY.toInt(),
      dstWidth.toInt(),
      dstHeight.toInt(),
      bufferMask.toInt(),
    ),
  );

  /// Bind framebuffer (FBO)
  void rlBindFramebuffer(
    num target,
    num framebuffer,
  ) => run(
    () => _debugLabels.rlBindFramebuffer(target, framebuffer),
    () => rl.RlglFlat.rlBindFramebuffer(
      target.toInt(),
      framebuffer.toInt(),
    ),
  );

  /// Enable color blending
  void rlEnableColorBlend() => run(
    () => _debugLabels.rlEnableColorBlend(),
    () => rl.RlglFlat.rlEnableColorBlend(),
  );

  /// Disable color blending
  void rlDisableColorBlend() => run(
    () => _debugLabels.rlDisableColorBlend(),
    () => rl.RlglFlat.rlDisableColorBlend(),
  );

  /// Enable depth test
  void rlEnableDepthTest() => run(
    () => _debugLabels.rlEnableDepthTest(),
    () => rl.RlglFlat.rlEnableDepthTest(),
  );

  /// Disable depth test
  void rlDisableDepthTest() => run(
    () => _debugLabels.rlDisableDepthTest(),
    () => rl.RlglFlat.rlDisableDepthTest(),
  );

  /// Enable depth write
  void rlEnableDepthMask() => run(
    () => _debugLabels.rlEnableDepthMask(),
    () => rl.RlglFlat.rlEnableDepthMask(),
  );

  /// Disable depth write
  void rlDisableDepthMask() => run(
    () => _debugLabels.rlDisableDepthMask(),
    () => rl.RlglFlat.rlDisableDepthMask(),
  );

  /// Enable backface culling
  void rlEnableBackfaceCulling() => run(
    () => _debugLabels.rlEnableBackfaceCulling(),
    () => rl.RlglFlat.rlEnableBackfaceCulling(),
  );

  /// Disable backface culling
  void rlDisableBackfaceCulling() => run(
    () => _debugLabels.rlDisableBackfaceCulling(),
    () => rl.RlglFlat.rlDisableBackfaceCulling(),
  );

  /// Color mask control
  void rlColorMask(
    bool r,
    bool g,
    bool b,
    bool a,
  ) => run(
    () => _debugLabels.rlColorMask(r, g, b, a),
    () => rl.RlglFlat.rlColorMask(
      r,
      g,
      b,
      a,
    ),
  );

  /// Set face culling mode
  void rlSetCullFace(
    RlCullMode mode,
  ) => run(
    () => _debugLabels.rlSetCullFace(mode),
    () => rl.RlglFlat.rlSetCullFace(
      mode.value,
    ),
  );

  /// Enable scissor test
  void rlEnableScissorTest() => run(
    () => _debugLabels.rlEnableScissorTest(),
    () => rl.RlglFlat.rlEnableScissorTest(),
  );

  /// Disable scissor test
  void rlDisableScissorTest() => run(
    () => _debugLabels.rlDisableScissorTest(),
    () => rl.RlglFlat.rlDisableScissorTest(),
  );

  /// Scissor test
  void rlScissor(
    num x,
    num y,
    num width,
    num height,
  ) => run(
    () => _debugLabels.rlScissor(x, y, width, height),
    () => rl.RlglFlat.rlScissor(
      x.toInt(),
      y.toInt(),
      width.toInt(),
      height.toInt(),
    ),
  );

  /// Enable point mode
  void rlEnablePointMode() => run(
    () => _debugLabels.rlEnablePointMode(),
    () => rl.RlglFlat.rlEnablePointMode(),
  );

  /// Disable point mode
  void rlDisablePointMode() => run(
    () => _debugLabels.rlDisablePointMode(),
    () => rl.RlglFlat.rlDisablePointMode(),
  );

  /// Set the point drawing size
  void rlSetPointSize(
    num size,
  ) => run(
    () => _debugLabels.rlSetPointSize(size),
    () => rl.RlglFlat.rlSetPointSize(
      size.toDouble(),
    ),
  );
  
  /// Get the point drawing size
  double rlGetPointSize() => run(
    () => _debugLabels.rlGetPointSize(),
    () => rl.RlglFlat.rlGetPointSize(),
  );

  /// Enable wire mode
  void rlEnableWireMode() => run(
    () => _debugLabels.rlEnableWireMode(),
    () => rl.RlglFlat.rlEnableWireMode(),
  );

  /// Disable wire mode
  void rlDisableWireMode() => run(
    () => _debugLabels.rlDisableWireMode(),
    () => rl.RlglFlat.rlDisableWireMode(),
  );

  /// Set the line drawing width
  void rlSetLineWidth(
    num width,
  ) => run(
    () => _debugLabels.rlSetLineWidth(width),
    () => rl.RlglFlat.rlSetLineWidth(
      width.toDouble(),
    ),
  );

  /// Get the line drawing width
  double rlGetLineWidth() => run(
    () => _debugLabels.rlGetLineWidth(),
    () => rl.RlglFlat.rlGetLineWidth(),
  );

  /// Enable line aliasing
  void rlEnableSmoothLines() => run(
    () => _debugLabels.rlEnableSmoothLines(),
    () => rl.RlglFlat.rlEnableSmoothLines(),
  );

  /// Disable line aliasing
  void rlDisableSmoothLines() => run(
    () => _debugLabels.rlDisableSmoothLines(),
    () => rl.RlglFlat.rlDisableSmoothLines(),
  );

  /// Enable stereo rendering
  void rlEnableStereoRender() => run(
    () => _debugLabels.rlEnableStereoRender(),
    () => rl.RlglFlat.rlEnableStereoRender(),
  );

  /// Disable stereo rendering
  void rlDisableStereoRender() => run(
    () => _debugLabels.rlDisableStereoRender(),
    () => rl.RlglFlat.rlDisableStereoRender(),
  );

  /// Check if stereo render is enabled
  bool rlIsStereoRenderEnabled() => run(
    () => _debugLabels.rlIsStereoRenderEnabled(),
    () => rl.RlglFlat.rlIsStereoRenderEnabled(),
  );

  /// Clear color buffer with color
  void rlClearColor(
    num r,
    num g,
    num b,
    num a,
  ) => run(
    () => _debugLabels.rlClearColor(r, g, b, a),
    () => rl.RlglFlat.rlClearColor(
      r.toInt(),
      g.toInt(),
      b.toInt(),
      a.toInt(),
    ),
  );

  /// Clear used screen buffers (color and depth)
  void rlClearScreenBuffers() => run(
    () => _debugLabels.rlClearScreenBuffers(),
    () => rl.RlglFlat.rlClearScreenBuffers(),
  );

  /// Check and log OpenGL error codes
  void rlCheckErrors() => run(
    () => _debugLabels.rlCheckErrors(),
    () => rl.RlglFlat.rlCheckErrors(),
  );

  /// Set blending mode
  void rlSetBlendMode(
    BlendMode mode,
  ) => run(
    () => _debugLabels.rlSetBlendMode(mode),
    () => rl.RlglFlat.rlSetBlendMode(
      mode.value,
    ),
  );

  /// Set blending mode factor and equation (using OpenGL factors)
  void rlSetBlendFactors(
    num glSrcFactor,
    num glDstFactor,
    num glEquation,
  ) => run(
    () => _debugLabels.rlSetBlendFactors(glSrcFactor, glDstFactor, glEquation),
    () => rl.RlglFlat.rlSetBlendFactors(
      glSrcFactor.toInt(),
      glDstFactor.toInt(),
      glEquation.toInt(),
    ),
  );

  /// Set blending mode factors and equations separately (using OpenGL factors)
  void rlSetBlendFactorsSeparate(
    num glSrcRGB,
    num glDstRGB,
    num glSrcAlpha,
    num glDstAlpha,
    num glEqRGB,
    num glEqAlpha,
  ) => run(
    () => _debugLabels.rlSetBlendFactorsSeparate(glSrcRGB, glDstRGB, glSrcAlpha, glDstAlpha, glEqRGB, glEqAlpha),
    () => rl.RlglFlat.rlSetBlendFactorsSeparate(
      glSrcRGB.toInt(),
      glDstRGB.toInt(),
      glSrcAlpha.toInt(),
      glDstAlpha.toInt(),
      glEqRGB.toInt(),
      glEqAlpha.toInt(),
    ),
  );

  /// Initialize rlgl (buffers, shaders, textures, states)
  void rlglInit(
    num width,
    num height,
  ) => run(
    () => _debugLabels.rlglInit(width, height),
    () => rl.RlglFlat.rlglInit(
      width.toInt(),
      height.toInt(),
    ),
  );

  /// De-initialize rlgl (buffers, shaders, textures)
  void rlglClose() => run(
    () => _debugLabels.rlglClose(),
    () => rl.RlglFlat.rlglClose(),
  );

  /// Get current OpenGL version
  int rlGetVersion() => run(
    () => _debugLabels.rlGetVersion(),
    () => rl.RlglFlat.rlGetVersion(),
  );

  /// Set current framebuffer width
  void rlSetFramebufferWidth(
    num width,
  ) => run(
    () => _debugLabels.rlSetFramebufferWidth(width),
    () => rl.RlglFlat.rlSetFramebufferWidth(
      width.toInt(),
    ),
  );

  /// Get default framebuffer width
  int rlGetFramebufferWidth() => run(
    () => _debugLabels.rlGetFramebufferWidth(),
    () => rl.RlglFlat.rlGetFramebufferWidth(),
  );

  /// Set current framebuffer height
  void rlSetFramebufferHeight(
    num height,
  ) => run(
    () => _debugLabels.rlSetFramebufferHeight(height),
    () => rl.RlglFlat.rlSetFramebufferHeight(
      height.toInt(),
    ),
  );

  /// Get default framebuffer height
  int rlGetFramebufferHeight() => run(
    () => _debugLabels.rlGetFramebufferHeight(),
    () => rl.RlglFlat.rlGetFramebufferHeight(),
  );

  /// Get default texture id
  int rlGetTextureIdDefault() => run(
    () => _debugLabels.rlGetTextureIdDefault(),
    () => rl.RlglFlat.rlGetTextureIdDefault(),
  );

  /// Get default shader id
  int rlGetShaderIdDefault() => run(
    () => _debugLabels.rlGetShaderIdDefault(),
    () => rl.RlglFlat.rlGetShaderIdDefault(),
  );

  /// Get default shader locations
  List<int> rlGetShaderLocsDefault() => run(
    () => _debugLabels.rlGetShaderLocsDefault(),
    () {
      final locs = rl.RlglFlat.rlGetShaderLocsDefault();
      return .generate(RL_MAX_SHADER_LOCATIONS, (i) => locs[i]);
    },
  );

  /// Load a render batch system
  RlRenderBatchD rlLoadRenderBatch(
    num numBuffers,
    num bufferElements,
  ) => run(
    () => _debugLabels.rlLoadRenderBatch(numBuffers, bufferElements),
    () => rl.RlglFlat.rlLoadRenderBatch(
      numBuffers.toInt(),
      bufferElements.toInt(),
    ),
  );

  /// Unload render batch system
  void rlUnloadRenderBatch(
    RlRenderBatchD batch,
  ) => run(
    () => _debugLabels.rlUnloadRenderBatch(batch),
    () => rl.RlglFlat.rlUnloadRenderBatch(
      batch,
    ),
  );

  /// Draw render batch data (Update->Draw->Reset)
  void rlDrawRenderBatch(
    RlRenderBatchD batch,
  ) => run(
    () => _debugLabels.rlDrawRenderBatch(batch),
    () => rl.Temp.RlRenderBatch$.RefUpdate1(batch,
      (pb) => rl.RlglFlat.rlDrawRenderBatch(
        pb,
      ),
    ),
  );

  /// Set the active render batch for rlgl (NULL for default internal)
  void rlSetRenderBatchActive([
    RlRenderBatchD? batch,
  ]) => run(
    () => _debugLabels.rlSetRenderBatchActive(batch),
    () => rl.Temp.RlRenderBatch$.RefUpdate1(batch,
      (pb) => rl.RlglFlat.rlSetRenderBatchActive(
        pb,
      ),
    ),
  );

  /// Update and draw internal render batch
  void rlDrawRenderBatchActive() => run(
    () => _debugLabels.rlDrawRenderBatchActive(),
    () => rl.RlglFlat.rlDrawRenderBatchActive(),
  );

  /// Check internal buffer overflow for a given number of vertex
  bool rlCheckRenderBatchLimit(
    num vCount,
  ) => run(
    () => _debugLabels.rlCheckRenderBatchLimit(vCount),
    () => rl.RlglFlat.rlCheckRenderBatchLimit(
      vCount.toInt(),
    ),
  );

  /// Set current texture for render batch and check buffers limits
  void rlSetTexture(
    num id,
  ) => run(
    () => _debugLabels.rlSetTexture(id),
    () => rl.RlglFlat.rlSetTexture(
      id.toInt(),
    ),
  );

  /// Load vertex array (vao) if supported
  int rlLoadVertexArray() => run(
    () => _debugLabels.rlLoadVertexArray(),
    () => rl.RlglFlat.rlLoadVertexArray(),
  );

  /// Load a vertex buffer object
  int rlLoadVertexBuffer(
    TypedDataList buffer,
    bool dynamic,
  ) => run(
    () => _debugLabels.rlLoadVertexBuffer(buffer, dynamic),
    () => rl.RlglFlat.rlLoadVertexBuffer(
      rl.Temp.TypedDataList$.Array(buffer),
      buffer.length,
      dynamic,
    ),
  );

  /// Load vertex buffer elements object
  int rlLoadVertexBufferElement(
    TypedDataList buffer,
    bool dynamic,
  ) => run(
    () => _debugLabels.rlLoadVertexBufferElement(buffer, dynamic),
    () => rl.RlglFlat.rlLoadVertexBufferElement(
      rl.Temp.TypedDataList$.Array(buffer),
      buffer.length,
      dynamic,
    ),
  );

  /// Update vertex buffer object data on GPU buffer
  void rlUpdateVertexBuffer(
    num bufferId,
    TypedDataList data,
    num dataSize,
    num offset,
  ) => run(
    () => _debugLabels.rlUpdateVertexBuffer(bufferId, data, dataSize, offset),
    () => rl.RlglFlat.rlUpdateVertexBuffer(
      bufferId.toInt(),
      rl.Temp.TypedDataList$.Array(data),
      (dataSize * rl.Temp.TypedDataList$.ElementSize(data)).toInt(),
      offset.toInt(),
    ),
  );

  /// Update vertex buffer elements data on GPU buffer
  void rlUpdateVertexBufferElements(
    num id,
    TypedDataList data,
    num dataSize,
    num offset,
  ) => run(
    () => _debugLabels.rlUpdateVertexBufferElements(id, data, dataSize, offset),
    () => rl.RlglFlat.rlUpdateVertexBufferElements(
      id.toInt(),
      rl.Temp.TypedDataList$.Array(data),
      (dataSize * rl.Temp.TypedDataList$.ElementSize(data)).toInt(),
      offset.toInt(),
    ),
  );

  /// Unload vertex array (vao)
  void rlUnloadVertexArray(
    num vaoId,
  ) => run(
    () => _debugLabels.rlUnloadVertexArray(vaoId),
    () => rl.RlglFlat.rlUnloadVertexArray(
      vaoId.toInt(),
    ),
  );

  /// Unload vertex buffer object
  void rlUnloadVertexBuffer(
    num vboId,
  ) => run(
    () => _debugLabels.rlUnloadVertexBuffer(vboId),
    () => rl.RlglFlat.rlUnloadVertexBuffer(
      vboId.toInt(),
    ),
  );

  /// Set vertex attribute data configuration
  void rlSetVertexAttribute(
    num index,
    num compSize,
    num type,
    bool normalized,
    num stride,
    num offset,
  ) => run(
    () => _debugLabels.rlSetVertexAttribute(index, compSize, type, normalized, stride, offset),
    () => rl.RlglFlat.rlSetVertexAttribute(
      index.toInt(),
      compSize.toInt(),
      type.toInt(),
      normalized,
      stride.toInt(),
      offset.toInt(),
    ),
  );

  /// Set vertex attribute data divisor
  void rlSetVertexAttributeDivisor(
    num index,
    num divisor,
  ) => run(
    () => _debugLabels.rlSetVertexAttributeDivisor(index, divisor),
    () => rl.RlglFlat.rlSetVertexAttributeDivisor(
      index.toInt(),
      divisor.toInt(),
    ),
  );

  /// Set vertex attribute default value, when attribute to provided
  void rlSetVertexAttributeDefault(
    num locIndex,
    Float32List value,
    RlShaderAttributeDataType attribType,
  ) => run(
    () => _debugLabels.rlSetVertexAttributeDefault(locIndex, value, attribType),
    () => rl.RlglFlat.rlSetVertexAttributeDefault(
      locIndex.toInt(),
      rl.Temp.Float32$.FromTypedList(value).cast(),
      attribType.value,
      value.length,
    ),
  );

  /// Draw vertex array (currently active vao)
  void rlDrawVertexArray(
    num offset,
    num count,
  ) => run(
    () => _debugLabels.rlDrawVertexArray(offset, count),
    () => rl.RlglFlat.rlDrawVertexArray(
      offset.toInt(),
      count.toInt(),
    ),
  );

  /// Draw vertex array elements
  void rlDrawVertexArrayElements(
    num offset,
    num count,
    Uint16List buffer,
  ) => run(
    () => _debugLabels.rlDrawVertexArrayElements(offset, count, buffer),
    () => rl.RlglFlat.rlDrawVertexArrayElements(
      offset.toInt(),
      count.toInt(),
      rl.Temp.Uint16$.FromTypedList(buffer).cast(),
    ),
  );

  /// Draw vertex array (currently active vao) with instancing
  void rlDrawVertexArrayInstanced(
    num offset,
    num count,
    num instances,
  ) => run(
    () => _debugLabels.rlDrawVertexArrayInstanced(offset, count, instances),
    () => rl.RlglFlat.rlDrawVertexArrayInstanced(
      offset.toInt(),
      count.toInt(),
      instances.toInt(),
    ),
  );

  /// Draw vertex array elements with instancing
  void rlDrawVertexArrayElementsInstanced(
    num offset,
    num count,
    Uint16List buffer,
    num instances,
  ) => run(
    () => _debugLabels.rlDrawVertexArrayElementsInstanced(offset, count, buffer, instances),
    () => rl.RlglFlat.rlDrawVertexArrayElementsInstanced(
      offset.toInt(),
      count.toInt(),
      rl.Temp.Uint16$.FromTypedList(buffer).cast(),
      instances.toInt(),
    ),
  );

  /// Load texture data
  int rlLoadTexture(
    Uint8List? data,
    num width,
    num height,
    PixelFormat format,
    num mipmapCount,
  ) => run(
    () => _debugLabels.rlLoadTexture(data, width, height, format, mipmapCount),
    () => rl.RlglFlat.rlLoadTexture(
      (data == null ? MemoryPointer.nullptr : rl.Temp.Uint8$.FromTypedList(data)).cast(),
      width.toInt(),
      height.toInt(),
      format.value,
      mipmapCount.toInt(),
    ),
  );

  /// Load depth texture/renderbuffer (to be attached to fbo)
  int rlLoadTextureDepth(
    num width,
    num height,
    bool useRenderBuffer,
  ) => run(
    () => _debugLabels.rlLoadTextureDepth(width, height, useRenderBuffer),
    () => rl.RlglFlat.rlLoadTextureDepth(
      width.toInt(),
      height.toInt(),
      useRenderBuffer,
    ),
  );

  /// Load texture cubemap data
  int rlLoadTextureCubemap(
    Uint8List? data,
    num size,
    PixelFormat format,
    num mipmapCount,
  ) => run(
    () => _debugLabels.rlLoadTextureCubemap(data, size, format, mipmapCount),
    () => rl.RlglFlat.rlLoadTextureCubemap(
      (data == null ? MemoryPointer.nullptr : rl.Temp.Uint8$.FromTypedList(data)).cast(),
      size.toInt(),
      format.value,
      mipmapCount.toInt(),
    ),
  );

  /// Update texture with new data on GPU
  void rlUpdateTexture(
    num id,
    num offsetX,
    num offsetY,
    num width,
    num height,
    PixelFormat format,
    Uint8List data,
  ) => run(
    () => _debugLabels.rlUpdateTexture(id, offsetX, offsetY, width, height, format, data),
    () => rl.RlglFlat.rlUpdateTexture(
      id.toInt(),
      offsetX.toInt(),
      offsetY.toInt(),
      width.toInt(),
      height.toInt(),
      format.value,
      rl.Temp.Uint8$.FromTypedList(data).cast(),
    ),
  );

  /// Get OpenGL internal formats
  (int glInternalFormat, int glFormat, int glType) rlGetGlTextureFormats(
    PixelFormat format,
  ) => run(
    () => _debugLabels.rlGetGlTextureFormats(format),
    () {
      final glInternalFormat = rl.Temp.UnsignedInt$.Ref1();
      final glFormat = rl.Temp.UnsignedInt$.Ref2();
      final glType = rl.Temp.UnsignedInt$.Ref3();
      rl.RlglFlat.rlGetGlTextureFormats(
        format.value,
        glInternalFormat,
        glFormat,
        glType,
      );
      return (glInternalFormat.value, glFormat.value, glType.value);
    },
  );

  /// Get name string for pixel format
  String rlGetPixelFormatName(
    PixelFormat format,
  ) => run(
    () => _debugLabels.rlGetPixelFormatName(format),
    () => rl.RlglFlat.rlGetPixelFormatName(
      format.value,
    ).toDartString(),
  );

  /// Unload texture from GPU memory
  void rlUnloadTexture(
    num id,
  ) => run(
    () => _debugLabels.rlUnloadTexture(id),
    () => rl.RlglFlat.rlUnloadTexture(
      id.toInt(),
    ),
  );

  /// Generate mipmap data for selected texture
  int rlGenTextureMipmaps(
    num id,
    num width,
    num height,
    PixelFormat format,
  ) => run(
    () => _debugLabels.rlGenTextureMipmaps(id, width, height, format),
    () {
      final mipmaps = rl.Temp.Int$.Ref1();
      rl.RlglFlat.rlGenTextureMipmaps(
        id.toInt(),
        width.toInt(),
        height.toInt(),
        format.value,
        mipmaps,
      );
      return mipmaps.value;
    },
  );

  /// Read texture pixel data
  Uint8List rlReadTexturePixels(
    num id,
    num width,
    num height,
    PixelFormat format,
  ) => run(
    () => _debugLabels.rlReadTexturePixels(id, width, height, format),
    () {
      final size = rl.CoreDart.GetPixelDataSize(
        width.toInt(),
        height.toInt(),
        format,
      );
      final pixels = rl.RlglFlat.rlReadTexturePixels(
        id.toInt(),
        width.toInt(),
        height.toInt(),
        format.value,
      );
      return pixels.to(size);
    },
  );

  /// Read screen pixel data (color buffer)
  Uint8List rlReadScreenPixels(
    num width,
    num height,
  ) => run(
    () => _debugLabels.rlReadScreenPixels(width, height),
    () {
      final values = rl.RlglFlat.rlReadScreenPixels(
        width.toInt(),
        height.toInt(),
      );
      final pixels = values.to<Uint8List>(width.toInt()*height.toInt()*4);
      values.free();
      return .fromList(pixels);
    },
  );

  /// Load an empty framebuffer
  int rlLoadFramebuffer() => run(
    () => _debugLabels.rlLoadFramebuffer(),
    () => rl.RlglFlat.rlLoadFramebuffer(),
  );

  /// Attach texture/renderbuffer to a framebuffer
  void rlFramebufferAttach(
    num fboId,
    num texId,
    RlFramebufferAttachType attachType,
    RlFramebufferAttachTextureType texType,
    num mipLevel,
  ) => run(
    () => _debugLabels.rlFramebufferAttach(fboId, texId, attachType, texType, mipLevel),
    () => rl.RlglFlat.rlFramebufferAttach(
      fboId.toInt(),
      texId.toInt(),
      attachType.value,
      texType.value,
      mipLevel.toInt(),
    ),
  );

  /// Verify framebuffer is complete
  bool rlFramebufferComplete(
    num id,
  ) => run(
    () => _debugLabels.rlFramebufferComplete(id),
    () => rl.RlglFlat.rlFramebufferComplete(
      id.toInt(),
    ),
  );

  /// Delete framebuffer from GPU
  void rlUnloadFramebuffer(
    num id,
  ) => run(
    () => _debugLabels.rlUnloadFramebuffer(id),
    () => rl.RlglFlat.rlUnloadFramebuffer(
      id.toInt(),
    ),
  );

  /// Copy framebuffer pixel data to internal buffer
  Uint8List rlCopyFramebuffer(
    num x,
    num y,
    num width,
    num height,
    PixelFormat format,
  ) => run(
    () => _debugLabels.rlCopyFramebuffer(x, y, width, height, format),
    () {
      final size = rl.CoreDart.GetPixelDataSize(width, height, format);
      if (size <= 0) {
        throw ArgumentError(
          'rlCopyFramebuffer: invalid pixel data size for '
          '${width}x$height @ $format',
        );
      }

      final pixels = rl.Temp.Uint8$.Sized(size);

      rl.RlglFlat.rlCopyFramebuffer(
        x.toInt(),
        y.toInt(),
        width.toInt(),
        height.toInt(),
        format.value,
        pixels.cast(),
      );

      return pixels.to(size);
    },
  );
  
  /// Resize internal framebuffer
  void rlResizeFramebuffer(
    num width,
    num height,
  ) => run(
    () => _debugLabels.rlResizeFramebuffer(width, height),
    () => rl.RlglFlat.rlResizeFramebuffer(
      width.toInt(),
      height.toInt(),
    ),
  );

  /// Load (compile) shader and return shader id
  int rlLoadShader(
    String code,
    RlShaderType type,
  ) => run(
    () => _debugLabels.rlLoadShader(code, type),
    () => rl.RlglFlat.rlLoadShader(
      rl.Temp.String$.ValueOrNull(code),
      type.value,
    ),
  );

  /// Load shader from code strings
  int rlLoadShaderProgram(
    String vsCode,
    String fsCode,
  ) => run(
    () => _debugLabels.rlLoadShaderProgram(vsCode, fsCode),
    () => rl.RlglFlat.rlLoadShaderProgram(
      rl.Temp.String$.ValueOrNull(vsCode),
      rl.Temp.String$.ValueOrNull(fsCode),
    ),
  );

  /// Load shader program, using already loaded shader ids
  int rlLoadShaderProgramEx(
    num vsId,
    num fsId,
  ) => run(
    () => _debugLabels.rlLoadShaderProgramEx(vsId, fsId),
    () => rl.RlglFlat.rlLoadShaderProgramEx(
      vsId.toInt(),
      fsId.toInt(),
    ),
  );
  
  /// Load compute shader program
  int rlLoadShaderProgramCompute(
    num csId,
  ) => run(
    () => _debugLabels.rlLoadShaderProgramCompute(csId),
    () => rl.RlglFlat.rlLoadShaderProgramCompute(
      csId.toInt(),
    ),
  );
  
  /// Unload shader, loaded with rlLoadShader();
  void rlUnloadShader(
    num id,
  ) => run(
    () => _debugLabels.rlUnloadShader(id),
    () => rl.RlglFlat.rlUnloadShader(
      id.toInt(),
    ),
  );

  /// Unload shader program
  void rlUnloadShaderProgram(
    num id,
  ) => run(
    () => _debugLabels.rlUnloadShaderProgram(id),
    () => rl.RlglFlat.rlUnloadShaderProgram(
      id.toInt(),
    ),
  );

  /// Get shader location uniform, requires shader program id
  int rlGetLocationUniform(
    num shaderId,
    String uniformName,
  ) => run(
    () => _debugLabels.rlGetLocationUniform(shaderId, uniformName),
    () => rl.RlglFlat.rlGetLocationUniform(
      shaderId.toInt(),
      rl.Temp.String$.ValueOrNull(uniformName),
    ),
  );

  /// Get shader location attribute, requires shader program id
  int rlGetLocationAttrib(
    num shaderId,
    String attribName,
  ) => run(
    () => _debugLabels.rlGetLocationAttrib(shaderId, attribName),
    () => rl.RlglFlat.rlGetLocationAttrib(
      shaderId.toInt(),
      rl.Temp.String$.ValueOrNull(attribName),
    ),
  );

  /// Set shader value uniform
  void rlSetUniform(
    num locIndex,
    TypedDataList value,
    RlShaderUniformDataType uniformType,
    num count,
  ) => run(
    () => _debugLabels.rlSetUniform(locIndex, value, uniformType, count),
    () {
      final MemoryPointer ptr;
      switch (uniformType) {
        case .RL_SHADER_UNIFORM_FLOAT:
        case .RL_SHADER_UNIFORM_VEC2:
        case .RL_SHADER_UNIFORM_VEC3:
        case .RL_SHADER_UNIFORM_VEC4:
          ptr = rl.Temp.Float32$.FromTypedData(value);
        case .RL_SHADER_UNIFORM_INT:
        case .RL_SHADER_UNIFORM_IVEC2:
        case .RL_SHADER_UNIFORM_IVEC3:
        case .RL_SHADER_UNIFORM_IVEC4:
        case .RL_SHADER_UNIFORM_SAMPLER2D:
          ptr = rl.Temp.Int32$.FromTypedData(value);
        case .RL_SHADER_UNIFORM_UINT:
        case .RL_SHADER_UNIFORM_UIVEC2:
        case .RL_SHADER_UNIFORM_UIVEC3:
        case .RL_SHADER_UNIFORM_UIVEC4:
          ptr = rl.Temp.Uint32$.FromTypedData(value);
      }
      rl.RlglFlat.rlSetUniform(
        locIndex.toInt(),
        ptr.cast(),
        uniformType.value,
        count.toInt(),
      );
    },
  );

  /// Set shader value matrix
  void rlSetUniformMatrix(
    num locIndex,
    MatrixD mat,
  ) => run(
    () => _debugLabels.rlSetUniformMatrix(locIndex, mat),
    () => rl.RlglFlat.rlSetUniformMatrix(
      locIndex.toInt(),
      mat,
    ),
  );

  /// Set shader value matrices
  void rlSetUniformMatrices(
    num locIndex,
    List<MatrixD> mat,
  ) => run(
    () => _debugLabels.rlSetUniformMatrices(locIndex, mat),
    () => rl.RlglFlat.rlSetUniformMatrices(
      locIndex.toInt(),
      rl.Temp.Matrix$.ArrayStruct(mat),
      mat.length,
    ),
  );

  /// Set shader value sampler
  void rlSetUniformSampler(
    num locIndex,
    num textureId,
  ) => run(
    () => _debugLabels.rlSetUniformSampler(locIndex, textureId),
    () => rl.RlglFlat.rlSetUniformSampler(
      locIndex.toInt(),
      textureId.toInt(),
    ),
  );

  /// Set shader currently active (id and locations)
  void rlSetShader(
    num id,
    List<int> locs,
  ) => run(
    () => _debugLabels.rlSetShader(id, locs),
    () => rl.RlglFlat.rlSetShader(
      id.toInt(),
      rl.Temp.Int$.Array(locs),
    ),
  );

  /// Dispatch compute shader (equivalent to *draw* for graphics pipeline)
  void rlComputeShaderDispatch(
    num groupX,
    num groupY,
    num groupZ,
  ) => run(
    () => _debugLabels.rlComputeShaderDispatch(groupX, groupY, groupZ),
    () => rl.RlglFlat.rlComputeShaderDispatch(
      groupX.toInt(),
      groupY.toInt(),
      groupZ.toInt(),
    ),
  );

  /// Load shader storage buffer object (SSBO)
  int rlLoadShaderBuffer(
    num size,
    TypedDataList? data,
    RlUsageHint? usageHint,
  ) => run(
    () => _debugLabels.rlLoadShaderBuffer(size, data, usageHint),
    () => rl.RlglFlat.rlLoadShaderBuffer(
      size.toInt(),
      data == null ? MemoryPointer.nullptr : rl.Temp.TypedDataList$.Array(data),
      usageHint?.value ?? 0,
    ),
  );

  /// Unload shader storage buffer object (SSBO)
  void rlUnloadShaderBuffer(
    num ssboId,
  ) => run(
    () => _debugLabels.rlUnloadShaderBuffer(ssboId),
    () => rl.RlglFlat.rlUnloadShaderBuffer(
      ssboId.toInt(),
    ),
  );

  /// Update SSBO buffer data
  void rlUpdateShaderBuffer(
    num id,
    TypedDataList data,
    num offset,
  ) => run(
    () => _debugLabels.rlUpdateShaderBuffer(id, data, offset),
    () => rl.RlglFlat.rlUpdateShaderBuffer(
      id.toInt(),
      rl.Temp.TypedDataList$.Array(data),
      data.length,
      offset.toInt(),
    ),
  );

  /// Bind SSBO buffer
  void rlBindShaderBuffer(
    num id,
    num index,
  ) => run(
    () => _debugLabels.rlBindShaderBuffer(id, index),
    () => rl.RlglFlat.rlBindShaderBuffer(
      id.toInt(),
      index.toInt(),
    ),
  );

  /// Read SSBO buffer data (GPU->CPU)
  Uint8List rlReadShaderBuffer(
    num id,
    num count,
    num offset,
  ) => run(
    () => _debugLabels.rlReadShaderBuffer(id, count, offset),
    () {
      final values = rl.Temp.Uint8$.Sized(count.toInt());
      rl.RlglFlat.rlReadShaderBuffer(
        id.toInt(),
        values.cast(),
        count.toInt(),
        offset.toInt(),
      );
      return values.to(count.toInt());
    },
  );

  /// Copy SSBO data between buffers
  void rlCopyShaderBuffer(
    num destId,
    num srcId,
    num destOffset,
    num srcOffset,
    num count,
  ) => run(
    () => _debugLabels.rlCopyShaderBuffer(destId, srcId, destOffset, srcOffset, count),
    () => rl.RlglFlat.rlCopyShaderBuffer(
      destId.toInt(),
      srcId.toInt(),
      destOffset.toInt(),
      srcOffset.toInt(),
      count.toInt(),
    ),
  );

  /// Get SSBO buffer size
  int rlGetShaderBufferSize(
    num id,
  ) => run(
    () => _debugLabels.rlGetShaderBufferSize(id),
    () => rl.RlglFlat.rlGetShaderBufferSize(
      id.toInt(),
    ),
  );

  /// Bind image texture
  void rlBindImageTexture(
    num id,
    num index,
    PixelFormat format,
    bool readonly,
  ) => run(
    () => _debugLabels.rlBindImageTexture(id, index, format, readonly),
    () => rl.RlglFlat.rlBindImageTexture(
      id.toInt(),
      index.toInt(),
      format.value,
      readonly,
    ),
  );

  /// Get internal modelview matrix
  MatrixD rlGetMatrixModelview() => run(
    () => _debugLabels.rlGetMatrixModelview(),
    () => rl.RlglFlat.rlGetMatrixModelview(),
  );

  /// Get internal projection matrix
  MatrixD rlGetMatrixProjection() => run(
    () => _debugLabels.rlGetMatrixProjection(),
    () => rl.RlglFlat.rlGetMatrixProjection(),
  );

  /// Get internal accumulated transform matrix
  MatrixD rlGetMatrixTransform() => run(
    () => _debugLabels.rlGetMatrixTransform(),
    () => rl.RlglFlat.rlGetMatrixTransform(),
  );

  /// Get internal projection matrix for stereo render (selected eye)
  MatrixD rlGetMatrixProjectionStereo(
    num eye,
  ) => run(
    () => _debugLabels.rlGetMatrixProjectionStereo(eye),
    () => rl.RlglFlat.rlGetMatrixProjectionStereo(eye.toInt()),
  );

  /// Get internal view offset matrix for stereo render (selected eye)
  MatrixD rlGetMatrixViewOffsetStereo(
    num eye,
  ) => run(
    () => _debugLabels.rlGetMatrixViewOffsetStereo(eye),
    () => rl.RlglFlat.rlGetMatrixViewOffsetStereo(eye.toInt()),
  );

  /// Set a custom projection matrix (replaces internal projection matrix)
  void rlSetMatrixProjection(
    MatrixD proj,
  ) => run(
    () => _debugLabels.rlSetMatrixProjection(proj),
    () => rl.RlglFlat.rlSetMatrixProjection(
      proj,
    ),
  );

  /// Set a custom modelview matrix (replaces internal modelview matrix)
  void rlSetMatrixModelview(
    MatrixD view,
  ) => run(
    () => _debugLabels.rlSetMatrixModelview(view),
    () => rl.RlglFlat.rlSetMatrixModelview(
      view,
    ),
  );

  /// Set eyes projection matrices for stereo rendering
  void rlSetMatrixProjectionStereo(
    MatrixD right,
    MatrixD left,
  ) => run(
    () => _debugLabels.rlSetMatrixProjectionStereo(right, left),
    () => rl.RlglFlat.rlSetMatrixProjectionStereo(
      right,
      left,
    ),
  );

  /// Set eyes view offsets matrices for stereo rendering
  void rlSetMatrixViewOffsetStereo(
    MatrixD right,
    MatrixD left,
  ) => run(
    () => _debugLabels.rlSetMatrixViewOffsetStereo(right, left),
    () => rl.RlglFlat.rlSetMatrixViewOffsetStereo(
      right,
      left,
    ),
  );

  /// Load and draw a cube
  void rlLoadDrawCube() => run(
    () => _debugLabels.rlLoadDrawCube(),
    () => rl.RlglFlat.rlLoadDrawCube(),
  );

  /// Load and draw a quad
  void rlLoadDrawQuad() => run(
    () => _debugLabels.rlLoadDrawQuad(),
    () => rl.RlglFlat.rlLoadDrawQuad(),
  );
}
